### ISSUE TITLE
need to change link to tw from ellaismcoin to ellaismproject

### ISSUE THREAD

**Issue by kubu00** [ellaism/ellawallet#9]
https://github.com/ellaism/ellawallet/blob/e7ac32930c8a73916fbc70d6e22e6dafecf66f70/app/includes/footer.tpl#L83

and add href to discord

**Comment by tk0221** [comment]
Would you like to make PR for that? and tag ellaismer will merge PR.

**Comment by kubu00** [comment]
kk
